---

# Targeting specific OSes or distributions:
#
#   - `ansible_system`               → Linux, BSD, ...
#   - `ansible_os_family`            → Debian, RedHat, ...
#   - `ansible_distribution`         → Debian, Ubuntu, RedHat, ...
#   - `ansible_distribution_release` → precise, wheezy, ...
#   - `ansible_pkg_mgr`              → apt, yum, ...

- name: Add official APT repository
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt_repository:
    repo: "deb http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/ {{ansible_distribution_release}} varnish-{{varnish_version}}"
  tags:
    - repo
    - varnish
    - http-cache

- name: Retrieve repo signing key
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt_key:
    url: "http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/GPG-key.txt"
  tags:
    - repo
    - varnish
    - http-cache

- name: Update repository caches
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt: update_cache=yes
  tags:
    - repo
    - varnish
    - http-cache

- name: Install Varnish
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt: name=varnish state=present
  tags:
    - deps
    - varnish
    - http-cache
